# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('datapoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.DataPoint')),
                ('description', models.CharField(max_length=1000)),
            ],
            bases=('locations.datapoint',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('datapoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.DataPoint')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('locations.datapoint',),
        ),
    ]
