# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_seed_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('datapoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.DataPoint')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('locations.datapoint',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('datapoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.DataPoint')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            bases=('locations.datapoint',),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('datapoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.DataPoint')),
            ],
            bases=('locations.datapoint',),
        ),
    ]
